import { db } from "../src/lib/db"

interface SeedJob {
  title: string
  company: string
  location: string
  remote: boolean
  salaryMin: number
  salaryMax: number
  tags: string[]
  category: string
  seniority: string
  description: string
}

const BASE_JOBS: SeedJob[] = [
  {"title":"Senior Frontend Engineer","company":"SonarSource","location":"Austin, TX","remote":true,"salaryMin":142000,"salaryMax":191000,"tags":["React","TypeScript","AWS","SonarQube","REST API"],"category":"Engineering","seniority":"senior","description":"Build and maintain SonarQube Cloud and Server frontends. Collaborate with product and UX to design and deliver features, write unit/integration/e2e tests, perform code reviews, mentor engineers, participate in on-call rotations, and resolve production issues while engaging with the user community.\n\nSonarSource is a leader in code quality and security solutions, trusted by thousands of organizations worldwide. Join a team that values clean code, continuous improvement, and developer empowerment."},
  {"title":"Partner Enablement Program Manager","company":"SonarSource","location":"Austin, TX","remote":true,"salaryMin":140000,"salaryMax":193000,"tags":["LMS","Digital Credentialing","Partner Strategy","Curriculum Design","Cross-functional Leadership"],"category":"Product","seniority":"senior","description":"Design, launch, and operate a partner accreditation program: curriculum design, LMS management, digital credentialing, assessments, reporting, and cross-functional coordination to enable partner-led revenue.\n\nThis role sits at the intersection of product, education, and go-to-market strategy. You'll build the systems that help partners succeed and drive measurable revenue impact."},
  {"title":"Enterprise Data Architect","company":"RSM US","location":"United States","remote":true,"salaryMin":142000,"salaryMax":191000,"tags":["Databricks","Microsoft Fabric","Power BI","Dynamics 365","Workday","Data Governance"],"category":"Engineering","seniority":"senior","description":"The Enterprise Data Architect will design and govern data architecture, create enterprise data models, and ensure data consistency across various systems.\n\nYou'll work with cutting-edge Microsoft data technologies to help clients modernize their data estates and drive business intelligence at scale."},
  {"title":"Product Manager — Talent Acquisition","company":"Lowe's","location":"Mooresville, NC","remote":true,"salaryMin":112000,"salaryMax":250000,"tags":["Product Strategy","Agile","OKRs","Data Analytics","HR Tech"],"category":"Product","seniority":"mid","description":"Own the vision, roadmap, and feature definition for assigned products. Write stories and requirements, prioritize backlog, define OKRs, measure customer success metrics, lead agile ceremonies, partner with engineering and stakeholders, and use data to drive product decisions and adoption.\n\nYou'll shape the future of how Lowe's attracts, hires, and retains top talent across one of the largest retail workforces in North America."},
  {"title":"Head of Strategic Product Sales","company":"Stripe","location":"United States","remote":true,"salaryMin":245000,"salaryMax":368000,"tags":["SaaS Sales","Fintech","Enterprise","Go-to-Market","Revenue Strategy"],"category":"Sales","seniority":"expert","description":"Lead and scale a Product Sales overlay team to drive adoption, expansion, and revenue for strategic products. Own commercial strategy, operating model, go-to-market plays, and cross-functional launch and enablement.\n\nPartner with AEs, AMs, Product, RevOps, and Marketing to prioritize opportunities, shape deal strategy, and deliver customer-facing executive engagement to maximize product penetration and outcomes."},
  {"title":"Senior Java Backend Engineer","company":"Fidelity Investments","location":"Garden City, FL","remote":true,"salaryMin":140000,"salaryMax":193000,"tags":["Java","Spring Boot","Kafka","Snowflake","Microservices","Redis"],"category":"Engineering","seniority":"senior","description":"Lead architecture and hands-on development of high-performance Java/Spring Boot back-end systems, build microservices and event-driven data pipelines, integrate Snowflake/SQL Server/Redis/Kafka, mentor engineers, drive code quality, performance tuning, and cross-functional delivery for post-trade accounting systems.\n\nFidelity's technology teams power some of the most critical financial infrastructure in the world. You'll work on systems that process billions of transactions with zero tolerance for error."},
  {"title":"Senior Data Engineer — Portfolio Risk","company":"JPMorgan Chase","location":"New York, NY","remote":true,"salaryMin":170000,"salaryMax":225000,"tags":["Python","SQL","AI/ML","Risk Modeling","Data Quality","Big Data"],"category":"Engineering","seniority":"senior","description":"Lead data domain for global portfolio risk models, owning data quality, validation, QC frameworks, and onboarding of model inputs and derived datasets. Partner with modeling, engineering, and upstream providers to ensure data accuracy, traceability, and integration into modeling workflows while driving cross-functional delivery and governance.\n\nThis is a high-impact role at the intersection of data engineering, quantitative finance, and risk management."},
  {"title":"Product Manager — Credit & Identity","company":"TransUnion","location":"Pittsburgh, PA","remote":true,"salaryMin":112000,"salaryMax":250000,"tags":["Product Strategy","Fintech","Identity Protection","Data Analytics","MarTech"],"category":"Product","seniority":"senior","description":"Lead product strategy and execution for credit monitoring, financial wellness, and identity protection platforms. Drive customer engagement, retention, and business outcomes through insights, roadmaps, partnerships, analytics, and cross-functional delivery.\n\nBuild business cases, define KPIs, manage third-party partners, and support risk/compliance while mentoring product staff."},
  {"title":"Senior Product Designer — Design Systems","company":"Binance","location":"Remote","remote":true,"salaryMin":140000,"salaryMax":200000,"tags":["Figma","Design Systems","Web3","Accessibility","Cross-functional Collaboration"],"category":"Design","seniority":"senior","description":"Lead the design of BNDS (Binance Design System): Iterate on the foundational framework and core components, optimize relevant state logic, and ensure compatibility with multiple platforms and real business scenario requirements.\n\nBuild and maintain the BNDS documentation system and asset library. Deeply adapt design solutions to business scenarios and drive design implementation through cross-functional collaboration."},
  {"title":"Full Stack Engineer","company":"Halter","location":"Remote","remote":true,"salaryMin":140000,"salaryMax":190000,"tags":["React","Node.js","IoT","AWS","TypeScript","Agriculture Tech"],"category":"Engineering","seniority":"mid","description":"Drive new business and manage customer success across your territory by prospecting, conducting in-field sales and demos, onboarding customers, expanding accounts, and providing field feedback to internal teams.\n\nHalter is revolutionizing agriculture with virtual fencing and precision livestock management. Join a team building technology that helps farmers work smarter and more sustainably."},
  {"title":"Operations Specialist — Banking","company":"Apex Fintech","location":"Dallas, TX","remote":true,"salaryMin":50000,"salaryMax":75000,"tags":["Banking Operations","ACH","Wires","Compliance","Excel","Claude"],"category":"Operations","seniority":"junior","description":"Execute day-to-day banking transactions (checks, wires, ACH) with accuracy and timeliness, handle exceptions and escalations, follow banking SOPs and regulatory requirements, assist with daily controls and reporting, support cross-functional requests, and propose/process workflow improvements under senior guidance.\n\nThis is an excellent entry point into fintech operations with clear growth pathways."},
  {"title":"Creative Strategist — Performance Marketing","company":"Meology","location":"Remote","remote":true,"salaryMin":85000,"salaryMax":120000,"tags":["Performance Marketing","Creative Strategy","Digital Advertising","A/B Testing","Data Analysis"],"category":"Marketing","seniority":"mid","description":"We're looking for a sharp, ambitious marketing leader to own everything from the big strategy to the granular execution — and genuinely love doing it.\n\nYou'll lead creative strategy for performance marketing campaigns across multiple channels, driving measurable ROI through compelling creative concepts and rigorous testing."},
  {"title":"Junior Frontend Engineer","company":"Linear","location":"New York, NY","remote":false,"salaryMin":80000,"salaryMax":110000,"tags":["React","TypeScript","CSS","Figma"],"category":"Engineering","seniority":"junior","description":"Linear is looking for a Junior Frontend Engineer to join our growing team. You'll work alongside senior engineers to build and refine the user interface of our issue tracking and project management tool.\n\nThis is an excellent opportunity to grow your skills in a supportive environment. You'll receive dedicated mentorship, participate in code reviews, and contribute to real features that ship to thousands of users.\n\nWe value curiosity, attention to detail, and a willingness to learn. If you're early in your career and passionate about crafting great developer experiences, we'd love to hear from you."},
  {"title":"Product Designer — Industrial Design","company":"Flusi","location":"Remote","remote":true,"salaryMin":110000,"salaryMax":160000,"tags":["Industrial Design","Hardware","CAD","Prototyping","3D Modeling"],"category":"Design","seniority":"mid","description":"We're looking for a Product Designer to own the industrial design of Flusi Alpha — shaping how our hardware looks, feels, and integrates into users' lives.\n\nFlusi is building next-generation consumer hardware. You'll work closely with mechanical engineers, electrical engineers, and manufacturing partners to bring beautiful, functional products to market."},
  {"title":"Technical Project Manager","company":"EVI","location":"Remote","remote":true,"salaryMin":120000,"salaryMax":165000,"tags":["Project Management","E-commerce","Agile","Jira","Stakeholder Management"],"category":"Product","seniority":"senior","description":"We are looking for a Technical Project Manager to lead complex digital and e-commerce projects within our IT & UX team. This role is ideal for a seasoned project manager who thrives in fast-paced environments and can bridge the gap between technical teams and business stakeholders.\n\nEVI creates platforms that live in kindergartens across the territory, helping the next generation of digital natives learn, grow, and thrive."},
  {"title":"Facebook Ads Specialist","company":"FuzionGrow","location":"Remote","remote":true,"salaryMin":60000,"salaryMax":90000,"tags":["Facebook Ads","Media Buying","Performance Marketing","Analytics","ROI Optimization"],"category":"Marketing","seniority":"mid","description":"We are looking for a Facebook Ads Specialist to join our media buying team to work across multiple international markets. This is a fast-paced, data-driven role where you'll manage six-figure monthly ad budgets and drive measurable growth for our clients.\n\nYou'll optimize campaigns, test creatives, and scale winning strategies across diverse markets and verticals."},
  {"title":"Graphic Designer + Video Editor","company":"FuzionGrow","location":"Remote","remote":true,"salaryMin":55000,"salaryMax":80000,"tags":["Graphic Design","Video Editing","Branding","Figma","Adobe Creative Suite","Motion Graphics"],"category":"Design","seniority":"mid","description":"Equipping our partners with the tools, narratives, and visuals they need to win and ensuring they are successfully activated and thriving.\n\nYou'll create compelling visual content across digital and print channels, edit video content for social media and ads, and maintain brand consistency across all touchpoints."},
  {"title":"Junior UI/UX Designer","company":"Soulism Lab","location":"Remote","remote":true,"salaryMin":50000,"salaryMax":75000,"tags":["UI Design","UX Design","Figma","Prototyping","User Research"],"category":"Design","seniority":"junior","description":"We are looking for a passionate and creative Junior UI/UX Designer to join our dynamic team. In this role, you will support the end-to-end design process from user research and wireframing to high-fidelity prototypes and design handoff.\n\nThis is a great opportunity to grow your design skills while working on real products used by real people."},
  {"title":"Backend Engineer","company":"Arc.dev Partner","location":"Remote","remote":true,"salaryMin":130000,"salaryMax":180000,"tags":["Node.js","Python","PostgreSQL","AWS","Microservices","API Design"],"category":"Engineering","seniority":"mid","description":"As a Backend Engineer, you'll be responsible for crafting usable, adaptable, reliable, and secure software. You'll use the latest lean and agile methodologies to build microservices that power a platform serving thousands of users daily.\n\nThis role offers significant ownership and the chance to shape backend architecture decisions."},
  {"title":"Quantitative Researcher","company":"Crypto Exchange","location":"Remote","remote":true,"salaryMin":180000,"salaryMax":280000,"tags":["Quantitative Finance","Python","C++","Machine Learning","Crypto","Risk Modeling"],"category":"Engineering","seniority":"senior","description":"Our client, a reputable global crypto exchange, is actively seeking a quant researcher to join their expanding team. The successful candidate will develop and refine trading algorithms, risk models, and market-making strategies.\n\nYou'll work with massive datasets and cutting-edge machine learning techniques in one of the fastest-moving markets in finance."},
  {"title":"Ad Graphic Designer","company":"STERRY","location":"Remote","remote":true,"salaryMin":60000,"salaryMax":90000,"tags":["Graphic Design","AI Tools","Ad Creative","Data-Driven Design","Canva","Figma"],"category":"Design","seniority":"mid","description":"STERRY is seeking a creative, data-driven, and AI-fluent Ad Graphic Designer to join our marketing team. In this role, you will transform strategic briefs into high-performing ad creatives across Meta, Google, and programmatic channels.\n\nYou'll leverage AI design tools to scale creative production while maintaining brand quality and performance standards."},
  {"title":"Shopify Manager","company":"Eirmon Solutions","location":"Remote","remote":true,"salaryMin":70000,"salaryMax":110000,"tags":["Shopify","E-commerce","Store Management","SEO","Conversion Optimization"],"category":"Marketing","seniority":"mid","description":"We're seeking a Shopify Manager to lead the charge in building and scaling regionally adapted Shopify storefronts that resonate with local markets.\n\nYou'll own the full Shopify ecosystem — from theme customization and app integration to SEO optimization and conversion rate improvements."},
  {"title":"Web Development Intern","company":"ChillBase","location":"Remote","remote":true,"salaryMin":20000,"salaryMax":35000,"tags":["HTML","CSS","JavaScript","React","Git","Learning"],"category":"Engineering","seniority":"junior","description":"We are seeking motivated candidates for Web Development Intern / Trainee to provide hands-on exposure to real-world web projects. This internship offers mentorship from senior developers and the opportunity to contribute to production code.\n\nIdeal for students or career-changers looking to build a foundation in modern web development."},
  {"title":"3D Motion Designer / CGI Artist","company":"Arc.dev Partner","location":"Remote","remote":true,"salaryMin":80000,"salaryMax":130000,"tags":["Blender","After Effects","Motion Graphics","3D Modeling","Cinema 4D"],"category":"Design","seniority":"mid","description":"Create stunning 3D motion graphics and CGI content for smartwatch feature videos and product launches. You'll bring hardware products to life through cinematic visual storytelling.\n\nThis role requires a blend of technical 3D skills and creative vision to produce content that captivates audiences."},
  {"title":"Senior Webflow Designer","company":"Arc.dev Partner","location":"Remote","remote":true,"salaryMin":90000,"salaryMax":140000,"tags":["Webflow","HTML/CSS","Conversion Optimization","Figma","CRO"],"category":"Design","seniority":"senior","description":"Senior Webflow Designer focused on Conversion Optimization. You'll design and build high-converting Webflow sites that drive measurable business results.\n\nThis role combines design craft with analytical rigor — you'll use data to inform design decisions and continuously optimize for conversion."},
  {"title":"H&B Support Specialist","company":"Inspira Financial","location":"United States","remote":true,"salaryMin":45000,"salaryMax":65000,"tags":["Customer Support","Healthcare","Financial Services","CRM","Communication"],"category":"Support","seniority":"junior","description":"Partner closely with accountholders calling our contact center to provide valuable support, education, and direction on products like Flexible Spending Accounts (FSA), Healthcare Savings Accounts (HSA), COBRA, and others.\n\nThis position is challenging, fast paced, and rewarding while delivering one superior quality experience at a time. Equipment provided including laptop, dual monitors, headset, and docking station."},
  {"title":"Social Media Strategist — Talent Brand","company":"Lowe's","location":"Mooresville, NC","remote":true,"salaryMin":75000,"salaryMax":110000,"tags":["Social Media","Employer Branding","Content Strategy","Analytics","Talent Acquisition"],"category":"Marketing","seniority":"mid","description":"Develop and execute social media strategies to attract talent, create and curate content, manage accounts and ads, engage the talent community, analyze performance, collaborate with HR/marketing, and respond to social inquiries to build Lowe's employer brand and drive candidate conversion.\n\nYou'll shape how one of America's largest employers shows up on social platforms."},
  {"title":"Senior Art Director","company":"Meology","location":"Remote","remote":true,"salaryMin":120000,"salaryMax":170000,"tags":["Art Direction","Branding","Creative Leadership","Campaign Design","Team Management"],"category":"Design","seniority":"senior","description":"As a Senior Art Director at Meology, you'll report to the Creative Director and be a part of a creative team that pushes boundaries. You'll lead visual storytelling across campaigns, mentor junior designers, and ensure every piece of creative work meets the highest standards.\n\nThis is a leadership role for a visionary creative who wants to shape brand narratives at scale."},
  {"title":"Business Systems Analyst — Online Banking","company":"TransUnion","location":"Pittsburgh, PA","remote":true,"salaryMin":95000,"salaryMax":140000,"tags":["Business Analysis","Online Banking","Requirements Gathering","Process Improvement","Agile"],"category":"Product","seniority":"mid","description":"Serve as a business systems analyst consultant for online banking: gather and document requirements, recommend and configure cross-functional systems, support process improvements and release activities, monitor user experience, and provide senior-level consulting to business stakeholders.\n\nYou'll bridge the gap between business needs and technical solutions in the fintech space."},
  {"title":"Senior Product Manager — Packaging & Sustainability","company":"Tate's Bake Shop","location":"Chicago, IL","remote":true,"salaryMin":140000,"salaryMax":193000,"tags":["Product Management","Sustainability","Packaging","Automation","Supply Chain"],"category":"Product","seniority":"senior","description":"Lead the Packaging & Climate product end-to-end: define strategy and roadmaps, oversee lifecycle from ideation to retirement, align with CSO, translate business requirements into tech solutions, manage budgets and vendor partnerships, drive automation/digitalization for sustainability outcomes, ensure security/compliance, and coach direct reports.\n\nYou'll drive innovation in sustainable packaging while managing complex supply chain and manufacturing partnerships."},
  {"title":"Game Designer","company":"ChillBase","location":"Remote","remote":true,"salaryMin":75000,"salaryMax":115000,"tags":["Game Design","Unity","Mobile Games","RPG","System Design","Prototyping"],"category":"Design","seniority":"mid","description":"Join ChillBase as a Game Designer and help create immersive mobile RPG experiences. You'll design game systems, balance mechanics, create prototypes, and collaborate with artists and engineers to bring compelling gameplay to life.\n\nThis is a hands-on design role where your ideas directly shape the player experience."},
  {"title":"AI Technical Curriculum Developer","company":"SonarSource","location":"Austin, TX","remote":true,"salaryMin":115000,"salaryMax":155000,"tags":["Technical Writing","AI Tools","CI/CD","SonarQube","LMS","Curriculum Design"],"category":"Engineering","seniority":"mid","description":"Design and maintain partner and customer-facing technical courses, labs, and accreditation content for SonarQube. Collaborate with SMEs, Product, and Customer Success to publish and update LMS training, adapt materials for partner personas, and use AI tools to scale content development and assessments.\n\nYou'll combine technical depth with instructional design to create learning experiences that stick."},
]

async function main() {
  const employer = await db.user.findFirst({ where: { isEmployer: true } })
  if (!employer) throw new Error("No employer user found; register one before seeding search jobs")

  const variants = BASE_JOBS.flatMap((base, index) =>
    Array.from({ length: 3 }, (_, batch) => ({
      id: `search-seed-${index + 1}-${batch + 1}`,
      ...base,
      company: `${base.company} ${batch + 1}`,
      salaryMin: base.salaryMin + index * 1000,
      salaryMax: base.salaryMax + index * 1000,
      requirements: ["Requirement A"],
      responsibilities: ["Responsibility A"],
      employerId: employer.clerkId,
      expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    })),
  )

  const existing = await db.job.count({ where: { id: { in: variants.map((v) => v.id) } } })
  if (existing > 0) {
    console.log("Search seed jobs already present; skipping")
    return
  }

  await db.job.createMany({ data: variants, skipDuplicates: true })
  console.log(`Seeded ${variants.length} search jobs`)
}

main().finally(() => db.$disconnect())
